version: '3.9'

services:
  nginx:
    image: nginx:1.26
    platform: linux/x86_64
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - php-fpm
    networks:
      - myProject

  php-fpm:
    build:
      context: docker/php
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/conf.d/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}
    networks:
      - myProject

networks:
  myProject:
    driver: bridge
