# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
#  - push

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick, swoole

      - name: php version
        run: php -v

      - name: Install dependencies
        uses: "php-actions/composer@v6"
        env:
          COMPOSER: "composer.json"
        with:
          args: "--ignore-platform-reqs --optimize-autoloader"
          working_dir: "app"
          php_version: "8.3"

      - name: PHPUnit Tests My
        run: app/vendor/bin/phpunit --configuration=app/phpunit.xml app/tests/
