# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: "php-actions/composer@v6"
        env:
          COMPOSER: "composer.json"
        with:
          args: "--ignore-platform-reqs --optimize-autoloader"
          working_dir: "app"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 10.5
          bootstrap: app/vendor/autoload.php
          configuration: app/phpunit.xml
#          args: --coverage-text
