# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: "php-actions/composer@v6"
        env:
          COMPOSER: "composer.json"
        with:
          args: "--ignore-platform-reqs --optimize-autoloader"
          working_dir: "app"

      - name: cd to work directory
        run:

      - name: PHPUnit Tests My
        run: cd app && vendor/bin/phpunit tests/

